defaultSemverRangePrefix: ''

packageExtensions:
  chalk@5.0.0:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'
  '@runtyping/test-type-writers@*':
    dependencies:
      runtypes: 'npm:runtypes@*'
      zod: 'npm:zod@*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.0.cjs
